# Generated by Django 6.0.7 on 2026-07-27 08:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspace', '0003_tripmember_invite_token_tripmember_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notif_type', models.CharField(choices=[('expense_added', 'Expense Added'), ('budget_updated', 'Budget Updated'), ('photo_uploaded', 'Photo Uploaded'), ('member_joined', 'Member Joined'), ('settlement_paid', 'Settlement Paid')], max_length=20)),
                ('message', models.CharField(max_length=300)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='workspace.tripmember')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='workspace.trip')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
