# Generated by Django 6.0.7 on 2026-07-26 19:42

import django.db.models.deletion
import gallery.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspace', '0003_tripmember_invite_token_tripmember_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=gallery.models.media_upload_path)),
                ('media_type', models.CharField(choices=[('photo', 'Photo'), ('video', 'Video')], default='photo', max_length=10)),
                ('caption', models.CharField(blank=True, max_length=300)),
                ('is_favorite', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_items', to='workspace.trip')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_media', to='workspace.tripmember')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
