# Generated by Django 6.0.7 on 2026-07-25 20:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspace', '0002_trip_member_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantReservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('restaurant_name', models.CharField(max_length=200)),
                ('reservation_at', models.DateTimeField()),
                ('party_size', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_reservations', to='workspace.trip')),
            ],
            options={
                'ordering': ['reservation_at'],
            },
        ),
        migrations.CreateModel(
            name='StayBooking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hotel_name', models.CharField(max_length=200)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('confirmation_number', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stays', to='workspace.trip')),
            ],
            options={
                'ordering': ['check_in'],
            },
        ),
        migrations.CreateModel(
            name='TransportBooking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mode', models.CharField(choices=[('flight', 'Flight'), ('train', 'Train'), ('bus', 'Bus'), ('car', 'Car')], max_length=10)),
                ('operator', models.CharField(blank=True, max_length=150)),
                ('from_location', models.CharField(max_length=150)),
                ('to_location', models.CharField(max_length=150)),
                ('departure_at', models.DateTimeField()),
                ('arrival_at', models.DateTimeField(blank=True, null=True)),
                ('confirmation_number', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_bookings', to='workspace.trip')),
            ],
            options={
                'ordering': ['departure_at'],
            },
        ),
        migrations.CreateModel(
            name='TravelDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('document_type', models.CharField(choices=[('hotel_confirmation', 'Hotel Confirmation'), ('flight_ticket', 'Flight Ticket'), ('train_ticket', 'Train Ticket'), ('bus_ticket', 'Bus Ticket'), ('other', 'Other')], default='other', max_length=30)),
                ('file', models.FileField(upload_to='travel_documents/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='workspace.trip')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
