# Generated by Django 6.0.7 on 2026-07-27 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantreservation',
            name='address',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='staybooking',
            name='address',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
