# Generated by Django 6.0.7 on 2026-07-25 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='member_count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
