# Hand-written (not autogenerated as a single AddField) — adding a unique
# field to a table that already has real rows (both locally and in
# production) needs the field nullable first, backfilled with real unique
# values per row, then locked down to non-null+unique. A single AddField
# with a callable default computes ONE value for the whole table rebuild on
# SQLite, which fails the unique constraint immediately — confirmed by
# hitting exactly that IntegrityError while writing this.
import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def populate_invite_tokens(apps, schema_editor):
    TripMember = apps.get_model('workspace', 'TripMember')
    for member in TripMember.objects.all():
        member.invite_token = uuid.uuid4()
        member.save(update_fields=['invite_token'])


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0002_trip_member_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tripmember',
            name='user',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                related_name='trip_memberships', to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name='tripmember',
            name='status',
            field=models.CharField(
                choices=[('invited', 'Invited'), ('joined', 'Joined'), ('owner', 'Owner')],
                default='invited', max_length=10,
            ),
        ),
        migrations.AddField(
            model_name='tripmember',
            name='invite_token',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.RunPython(populate_invite_tokens, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='tripmember',
            name='invite_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
