# Generated by Django 6.0.7 on 2026-08-07 01:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0003_tripmember_invite_token_tripmember_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
